language: php

env:
  global:
    - DB=MYSQL CORE_RELEASE=master

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0

before_script:
    - git clone git://github.com/chillu/silverstripe-travis-support.git ~/travis-support
    - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
    - cd ~/builds/ss

script:
    - vendor/bin/phpunit graphql/tests
