---
Name: graphqlroutes
---
SilverStripe\Control\Director:
  rules:
    # Default admin route stage is draft
    graphql:
      Controller: 'SilverStripe\GraphQL\Controller'
      Stage: Stage
      Permissions:
        CMS_ACCESS: CMS_ACCESS
      Authenticator: SilverStripe\GraphQL\Auth\MemberAuthenticator
